version: '3'
services:
    redis:
        image: "redis:alpine"
        container_name: redis
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        #command: redis-server --appendonly yes
        ports:
            - "6379:6379"
        restart: unless-stopped
        #expose:
           # - "6379"
        networks:
            - mynetwork 
    web:
        image: "docker-library-m-s"
        build: .
        command: "node index.js"
        ports: 
            - "3004:3004"
        depends_on:
            - "mongo"
            - "redis"
        networks:
            - mynetwork 
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db
        networks:
            - mynetwork 
   
networks:
    mynetwork: 
        driver: bridge

volumes:

    db: